from PIL import Image as pil_image
from keras.preprocessing import image
from keras.applications.inception_resnet_v2 import InceptionResNetV2, preprocess_input, decode_predictions
import numpy as np

from io import BytesIO
import os
import sys
import socket


def start_server():
    model = InceptionResNetV2()
    kw_mapping = get_keyword_mapping()
    sock_path = "imclassif.sock"
    try:
        os.unlink(sock_path)
    except OSError:
        pass

    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.bind(sock_path)
    s.listen()

    print('Listening on socket ' + sock_path)

    while True:
        conn, _ = s.accept()
        try:
            while True:
                size = int.from_bytes(conn.recv(4), byteorder='big')
                print('Received a request to classify image of size ' + str(size))

                img = conn.recv(size, socket.MSG_WAITALL)
                try:
                    result = classify(model, kw_mapping, img)
                except:
                    result = ''

                result_bytes = str.encode(result)
                conn.send(len(result_bytes).to_bytes(4, byteorder='big'))
                conn.send(result_bytes)
        finally:
            conn.close()


def classify(model, kw_mapping, img_bytes):
    img = pil_image.open(BytesIO(img_bytes))
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = img.resize((299, 299), pil_image.NEAREST)
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    keywords = [pred[1] for pred in decode_predictions(preds, top=3)[0]]
    terms = ';'.join(','.join(kw_mapping[k]) for k in keywords)

    return terms

def get_keyword_mapping():
    fish_mapping = ['рыб', 'fish']
    bird_mapping = ['птич', 'птиц', 'пташк', 'птах', 'bird']
    snake_mapping = ['зме', 'snake', 'питон', 'python']
    spider_mapping = ['паук', 'пауч', 'spider']
    duck_mapping = ['утк', 'утин', 'duck']
    crab_mapping = ['краб', 'crab']
    dog_mapping = ['собак', 'собач', 'собак', 'пес', 'псы',
                   'псин', 'щенок', 'дог', 'догг', 'dog', 'doge']
    cat_mapping = ['кот', 'кошк', 'кошач', 'котят', 'котенок', 'cat']
    butterfly_mapping = ['бабочк', 'butterfly']
    bear_mapping = ['медвед', 'bear']
    boar_mapping = ['кабан', 'кабанчик']
    monkey_mapping = ['обезья', 'monkey']
    coffee_mapping = ['коф', 'кофейн', 'coffee']
    ship_mapping = ['судн', 'корабл']
    mushroom_mapping = ['гриб', 'грибн']

    return {
        'tench': fish_mapping,
        'goldfish': fish_mapping,
        'great_white_shark': ['акул', 'shark'],
        'tiger_shark': ['акул', 'shark'],
        'hammerhead': ['акул', 'shark'],
        'electric_ray': ['скат', 'мор'],
        'stingray': ['скат', 'мор'],
        'cock': ['петух'],
        'hen': ['кур'],
        'ostrich': ['страус'],
        'brambling': bird_mapping,
        'goldfinch': bird_mapping,
        'house_finch': bird_mapping,
        'junco': bird_mapping,
        'indigo_bunting': bird_mapping,
        'robin': bird_mapping,
        'bulbul': bird_mapping + ['солов'],
        'jay': bird_mapping + ['сойк'],
        'magpie': bird_mapping,
        'chickadee': bird_mapping,
        'water_ouzel': bird_mapping,
        'kite': ['воздушн', 'зм'],
        'bald_eagle': ['штат', 'сша', 'америк'],
        'vulture': bird_mapping,
        'great_grey_owl': ['сов'],
        'European_fire_salamander': ['саламандр', 'земноводн', 'ящериц'],
        'common_newt': ['тритон', 'земноводн', 'ящериц'],
        'eft': ['тритон', 'земноводн', 'ящериц'],
        'spotted_salamander': ['саламандр', 'земноводн', 'ящериц'],
        'axolotl': ['аксолотл'],
        'bullfrog': ['лягушк'],
        'tree_frog': ['лягушк'],
        'tailed_frog': ['лягушк'],
        'loggerhead': ['череп', 'черепах'],
        'leatherback_turtle': ['череп', 'черепах'],
        'mud_turtle': ['череп', 'черепах'],
        'terrapin': ['череп', 'черепах'],
        'box_turtle': ['череп', 'черепах'],
        'banded_gecko': ['геккон', 'ящериц'],
        'common_iguana': ['игуа', 'игуан', 'ящериц'],
        'American_chameleon': ['хамелеон', 'ящериц'],
        'whiptail': ['ящериц'],
        'agama': ['ящериц'],
        'frilled_lizard': ['ящериц'],
        'alligator_lizard': ['ящериц'],
        'Gila_monster': ['ящериц'],
        'green_lizard': ['ящериц'],
        'African_chameleon': ['хамелеон', 'ящериц'],
        'Komodo_dragon': ['варан', 'ящер'],
        'African_crocodile': ['крокод', 'крокс'],
        'American_alligator': ['крокод', 'крокс', 'аллигатор'],
        'triceratops': ['динозавр'],
        'thunder_snake': snake_mapping,
        'ringneck_snake': snake_mapping,
        'hognose_snake': snake_mapping,
        'green_snake': snake_mapping,
        'king_snake': snake_mapping,
        'garter_snake': snake_mapping,
        'water_snake': snake_mapping,
        'vine_snake': snake_mapping,
        'night_snake': snake_mapping,
        'boa_constrictor': ['зме', 'удав'],
        'rock_python': snake_mapping,
        'Indian_cobra': snake_mapping + ['кобр'],
        'green_mamba': snake_mapping,
        'sea_snake': snake_mapping,
        'horned_viper': snake_mapping + ['гадюк'],
        'diamondback': snake_mapping,
        'sidewinder': snake_mapping,
        'trilobite': ['трилобит'],
        'harvestman': ['сенокосец'],
        'scorpion': spider_mapping + ['скорпион'],
        'black_and_gold_garden_spider': spider_mapping,
        'barn_spider': spider_mapping,
        'garden_spider': spider_mapping,
        'black_widow': spider_mapping,
        'tarantula': spider_mapping + ['тарантул'],
        'wolf_spider': spider_mapping,
        'tick': ['клещ'],
        'centipede': ['многоножк'],
        'black_grouse': bird_mapping + ['тетерев'],
        'ptarmigan': bird_mapping + ['куропатк'],
        'ruffed_grouse': bird_mapping + ['рябчик'],
        'prairie_chicken': bird_mapping + ['тетерев'],
        'peacock': bird_mapping + ['павлин'],
        'quail': bird_mapping + ['перепел'],
        'partridge': bird_mapping + ['куропатк'],
        'African_grey': ['попуг', 'попуга'],
        'macaw': ['попуг', 'попуга'],
        'sulphur-crested_cockatoo': ['какад', 'попуг', 'попуга'],
        'lorikeet': ['попуг', 'попуга'],
        'coucal': ['попуг', 'попуга'],
        'bee_eater': bird_mapping,
        'hornbill': bird_mapping,
        'hummingbird': bird_mapping + ['колибр'],
        'jacamar': bird_mapping,
        'toucan': bird_mapping + ['тукан'],
        'drake': duck_mapping + ['селезен'],
        'red-breasted_merganser': duck_mapping,
        'goose': ['гу', 'гус', 'goose'],
        'black_swan': ['лебед', 'лебедин'],
        'tusker': boar_mapping,
        'echidna': ['ехидн'],
        'platypus': ['утконос'],
        'wallaby': ['кенг', 'кенгур'],
        'koala': ['коал', 'коа'],
        'wombat': ['вомбат'],
        'jellyfish': ['медуз'],
        'sea_anemone': ['актин'],
        'brain_coral': ['коралл'],
        'flatworm': ['черв'],
        'nematode': ['паразит'],
        'conch': ['раковина'],
        'snail': ['улитк'],
        'slug': ['слизен', 'слизн'],
        'sea_slug': ['улитк'],
        'chiton': ['хитон', 'моллюск'],
        'chambered_nautilus': ['моллюск'],
        'Dungeness_crab': crab_mapping,
        'rock_crab': crab_mapping,
        'fiddler_crab': crab_mapping,
        'king_crab': crab_mapping,
        'American_lobster': ['лобстер', 'lobster'],
        'spiny_lobster': ['лобстер', 'lobster'],
        'crayfish': ['рак'],
        'hermit_crab': ['рак'],
        'isopod': ['мокриц'],
        'white_stork': bird_mapping + ['аист'],
        'black_stork': bird_mapping + ['аист'],
        'spoonbill': bird_mapping,
        'flamingo': ['фламинг', 'flamingo', 'kero'],
        'little_blue_heron': bird_mapping + ['цапл'],
        'American_egret': bird_mapping + ['цапл'],
        'bittern': bird_mapping,
        'crane': bird_mapping + ['журавл'],
        'limpkin': bird_mapping,
        'European_gallinule': bird_mapping,
        'American_coot': bird_mapping,
        'bustard': bird_mapping + ['дроф'],
        'ruddy_turnstone': bird_mapping,
        'red-backed_sandpiper': bird_mapping,
        'redshank': bird_mapping,
        'dowitcher': bird_mapping,
        'oystercatcher': bird_mapping,
        'pelican': ['пеликан', 'pelican'],
        'king_penguin': ['пингвин'],
        'albatross': bird_mapping + ['альбатрос'],
        'grey_whale': ['кит'],
        'killer_whale': ['кит'],
        'dugong': ['дюгоня'],
        'sea_lion': ['тюлен'],
        'Chihuahua': dog_mapping,
        'Japanese_spaniel': dog_mapping,
        'Maltese_dog': dog_mapping,
        'Pekinese': dog_mapping,
        'Shih-Tzu': dog_mapping,
        'Blenheim_spaniel': dog_mapping,
        'papillon': dog_mapping,
        'toy_terrier': dog_mapping,
        'Rhodesian_ridgeback': dog_mapping,
        'Afghan_hound': dog_mapping,
        'basset': dog_mapping,
        'beagle': dog_mapping,
        'bloodhound': dog_mapping,
        'bluetick': dog_mapping,
        'black-and-tan_coonhound': dog_mapping,
        'Walker_hound': dog_mapping,
        'English_foxhound': dog_mapping,
        'redbone': dog_mapping,
        'borzoi': dog_mapping,
        'Irish_wolfhound': dog_mapping,
        'Italian_greyhound': dog_mapping,
        'whippet': dog_mapping,
        'Ibizan_hound': dog_mapping,
        'Norwegian_elkhound': dog_mapping,
        'otterhound': dog_mapping,
        'Saluki': dog_mapping,
        'Scottish_deerhound': dog_mapping,
        'Weimaraner': dog_mapping,
        'Staffordshire_bullterrier': dog_mapping,
        'American_Staffordshire_terrier': dog_mapping,
        'Bedlington_terrier': dog_mapping,
        'Border_terrier': dog_mapping,
        'Kerry_blue_terrier': dog_mapping,
        'Irish_terrier': dog_mapping,
        'Norfolk_terrier': dog_mapping,
        'Norwich_terrier': dog_mapping,
        'Yorkshire_terrier': dog_mapping,
        'wire-haired_fox_terrier': dog_mapping,
        'Lakeland_terrier': dog_mapping,
        'Sealyham_terrier': dog_mapping,
        'Airedale': dog_mapping,
        'cairn': dog_mapping,
        'Australian_terrier': dog_mapping,
        'Dandie_Dinmont': dog_mapping,
        'Boston_bull': dog_mapping,
        'miniature_schnauzer': dog_mapping,
        'giant_schnauzer': dog_mapping,
        'standard_schnauzer': dog_mapping,
        'Scotch_terrier': dog_mapping,
        'Tibetan_terrier': dog_mapping,
        'silky_terrier': dog_mapping,
        'soft-coated_wheaten_terrier': dog_mapping,
        'West_Highland_white_terrier': dog_mapping,
        'Lhasa': dog_mapping,
        'flat-coated_retriever': dog_mapping,
        'curly-coated_retriever': dog_mapping,
        'golden_retriever': dog_mapping,
        'Labrador_retriever': dog_mapping,
        'Chesapeake_Bay_retriever': dog_mapping,
        'German_short-haired_pointer': dog_mapping,
        'vizsla': dog_mapping,
        'English_setter': dog_mapping,
        'Irish_setter': dog_mapping,
        'Gordon_setter': dog_mapping,
        'Brittany_spaniel': dog_mapping,
        'clumber': dog_mapping,
        'English_springer': dog_mapping,
        'Welsh_springer_spaniel': dog_mapping,
        'cocker_spaniel': dog_mapping,
        'Sussex_spaniel': dog_mapping,
        'Irish_water_spaniel': dog_mapping,
        'kuvasz': dog_mapping,
        'schipperke': dog_mapping,
        'groenendael': dog_mapping,
        'malinois': dog_mapping,
        'briard': dog_mapping,
        'kelpie': dog_mapping,
        'komondor': dog_mapping,
        'Old_English_sheepdog': dog_mapping,
        'Shetland_sheepdog': dog_mapping,
        'collie': dog_mapping,
        'Border_collie': dog_mapping,
        'Bouvier_des_Flandres': dog_mapping,
        'Rottweiler': dog_mapping,
        'German_shepherd': dog_mapping,
        'Doberman': dog_mapping,
        'miniature_pinscher': dog_mapping,
        'Greater_Swiss_Mountain_dog': dog_mapping,
        'Bernese_mountain_dog': dog_mapping,
        'Appenzeller': dog_mapping,
        'EntleBucher': dog_mapping,
        'boxer': dog_mapping,
        'bull_mastiff': dog_mapping,
        'Tibetan_mastiff': dog_mapping,
        'French_bulldog': dog_mapping,
        'Great_Dane': dog_mapping,
        'Saint_Bernard': dog_mapping,
        'Eskimo_dog': dog_mapping,
        'malamute': dog_mapping,
        'Siberian_husky': dog_mapping,
        'dalmatian': dog_mapping,
        'affenpinscher': dog_mapping,
        'basenji': dog_mapping,
        'pug': dog_mapping,
        'Leonberg': dog_mapping,
        'Newfoundland': dog_mapping,
        'Great_Pyrenees': dog_mapping,
        'Samoyed': dog_mapping,
        'Pomeranian': dog_mapping,
        'chow': dog_mapping,
        'keeshond': dog_mapping,
        'Brabancon_griffon': dog_mapping,
        'Pembroke': ['корг', 'corgi'],
        'Cardigan': ['корг', 'corgi'],
        'toy_poodle': dog_mapping,
        'miniature_poodle': dog_mapping,
        'standard_poodle': dog_mapping,
        'Mexican_hairless': dog_mapping,
        'timber_wolf': ['волк'],
        'white_wolf': ['волк'],
        'red_wolf': ['волк'],
        'coyote': ['койот'],
        'dingo': dog_mapping,
        'dhole': dog_mapping,
        'African_hunting_dog': dog_mapping,
        'hyena': ['гиен'],
        'red_fox': ['лис', 'fox'],
        'kit_fox': ['лис', 'fox'],
        'Arctic_fox': ['лис', 'fox'],
        'grey_fox': ['лис', 'fox'],
        'tabby': cat_mapping,
        'tiger_cat': cat_mapping,
        'Persian_cat': cat_mapping,
        'Siamese_cat': cat_mapping,
        'Egyptian_cat': cat_mapping,
        'cougar': ['пум'],
        'lynx': ['ры'],
        'leopard': ['леопард', 'leopard'],
        'snow_leopard': ['барс'],
        'jaguar': ['ягуар', 'jaguar'],
        'lion': ['лев', 'lion'],
        'tiger': ['тигр', 'tiger'],
        'cheetah': ['гепард', 'cheetah'],
        'brown_bear': bear_mapping,
        'American_black_bear': bear_mapping,
        'ice_bear': bear_mapping,
        'sloth_bear': bear_mapping,
        'mongoose': ['мангуст'],
        'meerkat': ['сурикат'],
        'tiger_beetle': ['жук'],
        'ladybug': ['бож'],
        'ground_beetle': ['жук'],
        'long-horned_beetle': ['жук'],
        'leaf_beetle': ['жук'],
        'dung_beetle': ['жук'],
        'rhinoceros_beetle': ['жук'],
        'weevil': ['жук'],
        'fly': ['мух'],
        'bee': ['пчел'],
        'ant': ['мурав'],
        'grasshopper': ['кузнечик'],
        'cricket': ['сверчок'],
        'walking_stick': ['трост'],
        'cockroach': ['таракан'],
        'mantis': ['богомол'],
        'cicada': ['цикад'],
        'leafhopper': ['цикад'],
        'lacewing': ['златоглазк'],
        'dragonfly': ['стрекоз'],
        'damselfly': ['стрекоз'],
        'admiral': butterfly_mapping,
        'ringlet': butterfly_mapping,
        'monarch': butterfly_mapping,
        'cabbage_butterfly': butterfly_mapping,
        'sulphur_butterfly': butterfly_mapping,
        'lycaenid': butterfly_mapping,
        'starfish': ['звезд'],
        'sea_urchin': ['мор', 'морск'],
        'sea_cucumber': ['мор', 'морск'],
        'wood_rabbit': ['кролик', 'rabbit'],
        'hare': ['заяц'],
        'Angora': ['кролик', 'rabbit'],
        'hamster': ['хомяк', 'хомяч', 'hamster'],
        'porcupine': ['дикобраз'],
        'fox_squirrel': ['белк', 'squirrel'],
        'marmot': ['сурок'],
        'beaver': ['бобр'],
        'guinea_pig': ['свинк'],
        'sorrel': ['щавел'],
        'zebra': ['зебр'],
        'hog': ['свин'],
        'wild_boar': boar_mapping,
        'warthog': boar_mapping,
        'hippopotamus': ['бегемот'],
        'ox': ['вол'],
        'water_buffalo': ['буйвол'],
        'bison': ['бизон'],
        'ram': ['баран'],
        'bighorn': ['баран'],
        'ibex': ['козел', 'козл'],
        'hartebeest': ['антилоп'],
        'impala': ['антилоп'],
        'gazelle': ['газел'],
        'Arabian_camel': ['верблюд', 'camel'],
        'llama': ['лам', 'llama'],
        'weasel': ['хорек', 'хорьк', 'weasel'],
        'mink': ['норк', 'mink'],
        'polecat': ['хорек', 'хорьк'],
        'black-footed_ferret': ['хорек', 'хорьк'],
        'otter': ['выдр'],
        'skunk': ['скунс', 'skunk'],
        'badger': ['барсук', 'badger'],
        'armadillo': ['броненосец'],
        'three-toed_sloth': ['ленивец'],
        'orangutan': monkey_mapping + ['орангутанг'],
        'gorilla': monkey_mapping + ['горилл', 'gorilla'],
        'chimpanzee': monkey_mapping + ['шимпанз', 'chimpanzee'],
        'gibbon': monkey_mapping,
        'siamang': monkey_mapping,
        'guenon': monkey_mapping,
        'patas': monkey_mapping,
        'baboon': monkey_mapping,
        'macaque': monkey_mapping,
        'langur': monkey_mapping,
        'colobus': monkey_mapping,
        'proboscis_monkey': monkey_mapping,
        'marmoset': monkey_mapping,
        'capuchin': monkey_mapping,
        'howler_monkey': monkey_mapping,
        'titi': monkey_mapping,
        'spider_monkey': monkey_mapping,
        'squirrel_monkey': monkey_mapping,
        'Madagascar_cat': ['фосс', 'fossa'],
        'indri': ['лемур', 'lemur'],
        'Indian_elephant': ['слон', 'elephant'],
        'African_elephant': ['слон', 'elephant'],
        'lesser_panda': ['панда', 'panda'],
        'giant_panda': ['панда', 'panda'],
        'barracouta': fish_mapping,
        'eel': ['eel', 'угор'],
        'coho': fish_mapping + ['salmon', 'лосос'],
        'rock_beauty': fish_mapping,
        'anemone_fish': fish_mapping,
        'sturgeon': fish_mapping + ['осетр'],
        'gar': fish_mapping,
        'lionfish': fish_mapping,
        'puffer': fish_mapping + ['иглобрюх', 'puffer'],
        'abacus': ['счет', 'счита'],
        'abaya': ['плат', 'dress', 'muslim', 'мусульманск'],
        'academic_gown': ['плат', 'dress'],
        'accordion': ['аккордеон', 'баян'],
        'acoustic_guitar': ['гитар', 'гитарн', 'guitar'],
        'aircraft_carrier': ['авианосец', 'авианосц'],
        'airliner': ['самолет'],
        'airship': ['дирижабл'],
        'altar': ['алтар', 'религ', 'религиозн'],
        'ambulance': ['скор', 'врач'],
        'amphibian': ['амфиб'],
        'analog_clock': ['час'],
        'apiary': ['пасек'],
        'apron': ['фартук'],
        'ashcan': ['мусор'],
        'assault_rifle': ['винтовк', 'оруж', 'пушк'],
        'backpack': ['рюкзак'],
        'bakery': ['пекарн'],
        'balance_beam': ['гимнастик', 'спорт'],
        'balloon': ['шарик'],
        'ballpoint': ['ручк'],
        'Band_Aid': ['лейкопластыр', 'пластыр'],
        'banjo': ['банджо', 'banjo', 'музык'],
        'bannister': ['перил'],
        'barber_chair': ['парикмахер', 'barbershop', 'барбершоп', 'парикмахерск', 'стрижк'],
        'barbershop': ['парикмахер', 'barbershop', 'барбершоп', 'парикмахерск', 'стрижк'],
        'barn': ['сара', 'barn', 'shed'],
        'barometer': ['барометр'],
        'barrel': ['бочк'],
        'barrow': ['тачк', 'тележк'],
        'baseball': ['бейсбол', 'baseball', 'спорт'],
        'basketball': ['баскетбол', 'баскет', 'basketball'],
        'bassinet': ['кроватк', 'ребенок', 'дет', 'детск'],
        'bassoon': ['оркестров', 'оркестр'],
        'bathing_cap': ['плаван', 'бассейн'],
        'bath_towel': ['полотенц'],
        'bathtub': ['ван'],
        'beach_wagon': ['тележк'],
        'beacon': ['маяк'],
        'beaker': ['хим', 'химическ', 'лаборатор'],
        'bearskin': ['британ', 'лондон', 'англ', 'королев'],
        'beer_bottle': ['пив'],
        'beer_glass': ['пив'],
        'bell_cote': ['колокол', 'церков', 'храм'],
        'bib': ['нагрудник'],
        'bicycle-built-for-two': ['велосипед', 'велик'],
        'bikini': ['бикин'],
        'binder': ['документ', 'офис'],
        'binoculars': ['бинокл'],
        'birdhouse': ['скворечник'],
        'boathouse': ['лодк'],
        'bobsled': ['сан', 'санк', 'зим'],
        'bolo_tie': ['украшен', 'одежд'],
        'bonnet': ['шапк', 'платок'],
        'bookcase': ['книг', 'книжн', 'bookshelf'],
        'bookshop': ['книг', 'книжн'],
        'bottlecap': ['бутылк', 'крышк'],
        'bow': ['лук'],
        'bow_tie': ['галстук', 'бабочк'],
        'brass': ['мемориальн', 'мемориал', 'памятник'],
        'brassiere': ['лифчик', 'bra'],
        'breakwater': ['волн', 'берег', 'мор'],
        'breastplate': ['брон', 'доспех'],
        'broom': ['метл', 'broom', 'witch'],
        'bucket': ['ведр', 'bucket'],
        'buckle': ['пряжк', 'ремен', 'ремн'],
        'bulletproof_vest': ['бронежилет', 'брон'],
        'bullet_train': ['поезд'],
        'butcher_shop': ['мяс', 'мясник'],
        'cab': ['такс'],
        'caldron': ['котел', 'котл', 'witch'],
        'candle': ['свеч', 'свечк'],
        'cannon': ['пушк'],
        'canoe': ['каноэ', 'лодк'],
        'can_opener': ['открывашк'],
        'cardigan': ['кардиган', 'жилет', 'жилетк'],
        'car_mirror': ['зеркал', 'машин', 'автомобил', 'тачк'],
        'carousel': ['карусел'],
        "carpenter's_kit": ['мастерск', 'дерев'],
        'carton': ['коробк'],
        'car_wheel': ['колес'],
        'cash_machine': ['касс'],
        'cassette': ['кассет', 'музык'],
        'cassette_player': ['кассет', 'плеер'],
        'castle': ['замок', 'замк'],
        'catamaran': ['катамаран'],
        'CD_player': ['cd', 'плеер', 'музык'],
        'cello': ['виолончел', 'оркестр', 'оркестров'],
        'cellular_telephone': ['телефон', 'смартфон', 'phone'],
        'chain': ['цеп'],
        'chainlink_fence': ['забор'],
        'chain_mail': ['кольчуг', 'доспех', 'рыцар'],
        'chain_saw': ['пил'],
        'chest': ['груд'],
        'chiffonier': ['тумб', 'комод'],
        'chime': ['колокол', 'музык'],
        'china_cabinet': ['посуд', 'посудн', 'шкаф'],
        'Christmas_stocking': ['рождество', 'christmas', 'чулок', 'подарок', 'подарк', 'праздник'],
        'church': ['церков'],
        'cinema': ['кинотеатр', 'кин'],
        'cleaver': ['нож'],
        'cliff_dwelling': ['скал'],
        'cloak': ['плащ'],
        'clog': ['обув'],
        'cocktail_shaker': ['коктейл', 'бар', 'вальхалл'],
        'coffee_mug': coffee_mapping + ['кружк'],
        'coffeepot': coffee_mapping,
        'coil': ['катушк'],
        'combination_lock': ['замок', 'замк'],
        'computer_keyboard': ['клавиатур', 'компьютер', 'комп'],
        'confectionery': ['булочк', 'пирожн'],
        'container_ship': ship_mapping,
        'convertible': ['кабриолет', 'машин'],
        'corkscrew': ['штопор'],
        'cornet': ['корнет', 'оркестр', 'оркестров'],
        'cowboy_boot': ['ковбой', 'cowboy', 'сапог', 'вестерн'],
        'cowboy_hat': ['ковбой', 'cowboy', 'шляп'],
        'cradle': ['колыбел'],
        'crash_helmet': ['шлем'],
        'crate': ['коробк'],
        'crib': ['кроватк', 'ребенок', 'дет', 'детск'],
        'Crock_Pot': ['кастрюл', 'мультиварк', 'вар'],
        'croquet_ball': ['мяч', 'мячик'],
        'crutch': ['костыл'],
        'cuirass': ['панцир'],
        'dam': ['дамб', 'гэс'],
        'desk': ['стол'],
        'desktop_computer': ['компьютер', 'комп', 'pc', 'computer'],
        'dial_telephone': ['телефон'],
        'diaper': ['подгузник', 'diaper'],
        'digital_clock': ['час'],
        'digital_watch': ['час'],
        'dining_table': ['стол'],
        'dishrag': ['тряпк', 'посуд'],
        'dishwasher': ['посудомоечн', 'посуд'],
        'disk_brake': ['тормоз'],
        'dock': ['док'],
        'dogsled': dog_mapping + ['упряжк'],
        'dome': ['купол'],
        'doormat': ['синдзи'],
        'drilling_platform': ['нефт'],
        'drum': ['барабан'],
        'drumstick': ['барабан', 'палочк'],
        'barbell': ['штанг', 'зал', 'кача', 'качалк'],
        'dumbbell': ['гантел', 'зал', 'кача', 'качалк'],
        'Dutch_oven': ['кастрюл'],
        'electric_fan': ['вентилятор'],
        'electric_guitar': ['гитар', 'guitar', 'рок'],
        'electric_locomotive': ['поезд', 'электричк'],
        'entertainment_center': ['телевизор', 'тв', 'телик'],
        'envelope': ['конверт'],
        'espresso_maker': coffee_mapping + ['эспрессо', 'espresso'],
        'face_powder': ['пудр', 'косметик'],
        'feather_boa': ['шарф', 'пер'],
        'file': ['ящик', 'офис'],
        'fireboat': ship_mapping + ['пожарн'],
        'fire_engine': ['пожарн'],
        'fire_screen': ['камин'],
        'flagpole': ['флаг'],
        'flute': ['флейт', 'музык'],
        'folding_chair': ['стул'],
        'football_helmet': ['шлем', 'футбол'],
        'forklift': ['грузоподъемник', 'эвакуатор'],
        'fountain': ['фонтан'],
        'fountain_pen': ['перьев', 'ручк'],
        'four-poster': ['кроват'],
        'freight_car': ['поезд', 'вагон'],
        'French_horn': ['музык', 'оркестр'],
        'frying_pan': ['сковород', 'сковородк'],
        'fur_coat': ['шуб'],
        'garbage_truck': ['мусоровоз', 'мусор'],
        'gasmask': ['противогаз'],
        'gas_pump': ['насос'],
        'goblet': ['кубок', 'chalice'],
        'go-kart': ['гонк'],
        'golf_ball': ['гольф'],
        'golfcart': ['гольф'],
        'gondola': ['лодк', 'гондол'],
        'gong': ['гонг'],
        'gown': ['плат'],
        'grand_piano': ['роял', 'пианин', 'piano'],
        'greenhouse': ['теплиц'],
        'grille': ['решетк', 'радиатор'],
        'grocery_store': ['магаз', 'магазин', 'пятерочк', 'магнит', 'дикс'],
        'guillotine': ['гильотин', 'казн'],
        'hair_slide': ['заколк', 'волос'],
        'hair_spray': ['лак', 'волос'],
        'half_track': ['гусениц', 'воен', 'military'],
        'hammer': ['молоток'],
        'hamper': ['корзин', 'корзинк'],
        'hand_blower': ['фен'],
        'hand-held_computer': ['компьютер', 'смартфон', 'планшет'],
        'handkerchief': ['платок', 'платк'],
        'hard_disc': ['hdd'],
        'harmonica': ['гармоник', 'музык'],
        'harp': ['арф', 'музык'],
        'harvester': ['комбайн', 'ферм', 'сельск'],
        'hatchet': ['топор'],
        'holster': ['кобур', 'пистолет'],
        'home_theater': ['кин', 'кинотеатр'],
        'honeycomb': ['сот', 'мед'],
        'hook': ['крюк'],
        'hoopskirt': ['юбк'],
        'horizontal_bar': ['перекладин', 'турник'],
        'horse_cart': ['кон', 'повозк'],
        'hourglass': ['песочн', 'час'],
        'iPod': ['ipod', 'apple'],
        'iron': ['утюг'],
        "jack-o'-lantern": ['halloween', 'хэллоуин', 'тыкв'],
        'jean': ['джинс', 'джинсов'],
        'jeep': ['джип'],
        'jersey': ['футболк'],
        'jigsaw_puzzle': ['пазл'],
        'jinrikisha': ['карет', 'каретн'],
        'joystick': ['джойстик', 'игр', 'videogame'],
        'kimono': ['кимон', 'япон', 'аним'],
        'knee_pad': ['наколенник', 'спорт', 'футбол', 'хокк'],
        'knot': ['узел', 'узл'],
        'lab_coat': ['лаборатор', 'лабораторн', 'лаб'],
        'ladle': ['кухн', 'повар'],
        'lampshade': ['абажур', 'ламп', 'lamp', 'lampshade'],
        'laptop': ['ноутбук', 'ноут', 'laptop'],
        'lawn_mower': ['газонокосилк', 'косилк', 'кос'],
        'lens_cap': ['объектив'],
        'letter_opener': ['нож', 'бумаг'],
        'library': ['библиотек', 'книг', 'чита'],
        'lifeboat': ['спасательн', 'спасател', 'шлюпк'],
        'lighter': ['зажигалк'],
        'limousine': ['лимузин', 'машин'],
        'liner': ['круиз', 'круизн', 'лайнер', 'титаник'],
        'lipstick': ['губн', 'губ', 'помад'],
        'Loafer': ['обув', 'обувн'],
        'lotion': ['лосьон', 'косметик'],
        'loudspeaker': ['громкоговорител', 'динамик', 'колонк'],
        'loupe': ['луп'],
        'lumbermill': ['лесопилк', 'пил'],
        'magnetic_compass': ['компас'],
        'mailbag': ['сумк', 'почт'],
        'mailbox': ['почт', 'почтов'],
        'maillot': ['купальник'],
        'manhole_cover': ['люк'],
        'maraca': ['маракас', 'музык'],
        'marimba': ['ксилофон', 'музык'],
        'mask': ['маск'],
        'matchstick': ['спичк'],
        'maypole': ['фестивал'],
        'maze': ['лабиринт'],
        'measuring_cup': ['мер', 'мерн'],
        'medicine_chest': ['аптечк'],
        'megalith': ['мегалит', 'стоунхендж', 'памятник'],
        'microphone': ['микрофон'],
        'microwave': ['микроволнов', 'микроволновк'],
        'military_uniform': ['воен', 'форм'],
        'milk_can': ['молок'],
        'minibus': ['микроавтобус', 'машин'],
        'miniskirt': ['юбк'],
        'minivan': ['минивэн', 'машин'],
        'missile': ['ракет'],
        'mitten': ['варежк', 'перчатк'],
        'mixing_bowl': ['миск', 'пиал', 'посуд'],
        'mobile_home': ['дом'],
        'Model_T': ['машин', 'форд', 'ford'],
        'modem': ['модем'],
        'monastery': ['монастыр'],
        'monitor': ['монитор'],
        'moped': ['мопед'],
        'mortar': ['ступ', 'миск', 'смешива', 'смеша', 'меша'],
        'mortarboard': ['универ', 'учеб', 'итм', 'бакалавриат', 'магистратур'],
        'mosque': ['мечет', 'мусульман', 'muslim'],
        'mosquito_net': ['сетк', 'москитн'],
        'motor_scooter': ['мопед', 'скутер', 'мотоцикл'],
        'mountain_bike': ['велосипед', 'велик'],
        'mountain_tent': ['палатк'],
        'mouse': ['мыш'],
        'mousetrap': ['мышеловк'],
        'moving_van': ['фургон', 'машин'],
        'muzzle': ['морд', 'мордочк', 'muzzle'],
        'nail': ['гвоздь'],
        'neck_brace': ['корсет', 'воротник', 'ше'],
        'necklace': ['ожерел', 'украшен'],
        'nipple': ['соск', 'бутылочк', 'детск'],
        'notebook': ['блокнот'],
        'obelisk': ['обелиск'],
        'oboe': ['музык', 'оркестр'],
        'ocarina': ['музык', 'флейт'],
        'odometer': ['одометр', 'спидометр'],
        'oil_filter': ['двигател'],
        'organ': ['орган'],
        'oscilloscope': ['осциллограф'],
        'overskirt': ['плат'],
        'oxcart': ['повозк'],
        'oxygen_mask': ['кислородн', 'маск'],
        'packet': ['пакет'],
        'paddle': ['весл'],
        'paddlewheel': ['лодк', 'судн'],
        'padlock': ['замок'],
        'paintbrush': ['кист', 'кисточк'],
        'pajama': ['пижам', 'pajama'],
        'palace': ['дворец', 'дворц'],
        'panpipe': ['флейт'],
        'paper_towel': ['полотенц'],
        'parachute': ['парашют'],
        'parallel_bars': ['гимнастик', 'брус'],
        'park_bench': ['скамейк'],
        'parking_meter': ['стоянк'],
        'passenger_car': ['машин'],
        'patio': ['терасс', 'веранд'],
        'pay-phone': ['телефон'],
        'pedestal': ['пьедестал'],
        'pencil_box': ['пенал', 'школ'],
        'pencil_sharpener': ['точилк', 'школ'],
        'perfume': ['дух'],
        'Petri_dish': ['бактер', 'вирус'],
        'photocopier': ['принтер', 'копиркин'],
        'pick': ['медиатор'],
        'pickelhaube': ['шлем', 'войн'],
        'picket_fence': ['забор'],
        'pickup': ['пикап', 'truck'],
        'pier': ['пирс'],
        'piggy_bank': ['копилк'],
        'pill_bottle': ['таблетк'],
        'pillow': ['подушк'],
        'ping-pong_ball': ['теннис'],
        'pinwheel': ['игрушк'],
        'pirate': ['пират', 'пиратск'],
        'pitcher': ['бейсбол'],
        'plane': ['самолет'],
        'planetarium': ['планетар'],
        'plastic_bag': ['пакет', 'пакетик'],
        'plate_rack': ['сушилк', 'посуд'],
        'plow': ['плуг'],
        'plunger': ['вантуз'],
        'Polaroid_camera': ['камер', 'фот', 'фотограф'],
        'pole': ['столб'],
        'police_van': ['полицейск', 'полиц'],
        'poncho': ['пончо'],
        'pool_table': ['бильярд'],
        'pop_bottle': ['кол', 'пепс', 'coca-cola'],
        'pot': ['горшок'],
        "potter's_wheel": ['гончар'],
        'power_drill': ['дрел', 'ремонт'],
        'prayer_rug': ['молитв'],
        'printer': ['принтер'],
        'prison': ['тюрьм'],
        'projectile': ['ракет'],
        'projector': ['проектор'],
        'puck': ['шайб', 'хокк'],
        'punching_bag': ['груш', 'бокс'],
        'purse': ['кошелек', 'кошельк'],
        'quill': ['пер', 'писа'],
        'quilt': ['одея', 'крова'],
        'racer': ['гонщик', 'гонк'],
        'racket': ['ракетк', 'теннис'],
        'radiator': ['радиатор'],
        'radio': ['рад'],
        'radio_telescope': ['телескоп', 'космос'],
        'rain_barrel': ['бочк'],
        'recreational_vehicle': ['машин'],
        'reel': ['катушк', 'бобин', 'пленк'],
        'reflex_camera': ['камер', 'зеркалк'],
        'refrigerator': ['холодильник'],
        'remote_control': ['пульт'],
        'restaurant': ['ресторан', 'столов', 'столовк'],
        'revolver': ['револьвер'],
        'rifle': ['руж'],
        'rocking_chair': ['кресл'],
        'rotisserie': ['мангал', 'шашлык'],
        'rubber_eraser': ['ластик', 'резинк'],
        'rugby_ball': ['мяч'],
        'rule': ['линейк'],
        'running_shoe': ['кроссовк', 'кросс'],
        'safe': ['сейф'],
        'safety_pin': ['булавк'],
        'saltshaker': ['солонк', 'сол'],
        'sandal': ['сандал'],
        'sarong': ['пляж', 'одежд'],
        'sax': ['саксофон'],
        'scabbard': ['ножн', 'катан'],
        'scale': ['вес'],
        'school_bus': ['школьн', 'автобус'],
        'schooner': ['шхун', 'парус', 'парусн'],
        'scoreboard': ['табл'],
        'screen': ['экран', 'монитор'],
        'screw': ['винт', 'шуруп'],
        'screwdriver': ['отвертк'],
        'seat_belt': ['ремен', 'пристегн', 'пристегнут', 'пристегнул'],
        'sewing_machine': ['швейн', 'нитк'],
        'shield': ['щит'],
        'shoe_shop': ['обув'],
        'shoji': ['япон', 'японск'],
        'shopping_basket': ['корзин', 'супермаркет'],
        'shopping_cart': ['корзин', 'супермаркет'],
        'shovel': ['лопат'],
        'shower_cap': ['шапочк'],
        'shower_curtain': ['душ'],
        'ski': ['лыж'],
        'ski_mask': ['лыж'],
        'sleeping_bag': ['спальник', 'поход'],
        'slide_rule': ['линейк'],
        'sliding_door': ['двер'],
        'slot': ['казин'],
        'snorkel': ['плыт', 'подводн'],
        'snowmobile': ['снегоход'],
        'snowplow': ['зим'],
        'soap_dispenser': ['мыл'],
        'soccer_ball': ['футбол', 'футбольн'],
        'sock': ['носок', 'носк'],
        'solar_dish': ['солнечн'],
        'sombrero': ['сомбрер', 'шляп'],
        'soup_bowl': ['тарелк'],
        'space_bar': ['пробел'],
        'space_heater': ['обогревател'],
        'space_shuttle': ['шаттл', 'космос'],
        'spatula': ['шпател'],
        'speedboat': ['катер', 'лодк'],
        'spider_web': ['паутин'],
        'spindle': ['нитк'],
        'sports_car': ['ламборгин', 'ламборджин', 'порш'],
        'spotlight': ['прожектор'],
        'stage': ['сцен'],
        'steam_locomotive': ['паровоз', 'поезд'],
        'steel_arch_bridge': ['мост'],
        'steel_drum': ['барабан'],
        'stethoscope': ['стетоскоп'],
        'stole': ['шарф'],
        'stone_wall': ['стен'],
        'stopwatch': ['секундомер'],
        'stove': ['плит'],
        'strainer': ['фильтр', 'сит'],
        'streetcar': ['трамва'],
        'stretcher': ['носилк'],
        'studio_couch': ['диван'],
        'stupa': ['буддизм'],
        'submarine': ['подлодк'],
        'suit': ['костюм', 'пиджак'],
        'sundial': ['час', 'солнечн'],
        'sunglass': ['солнечн'],
        'sunglasses': ['очк', 'sunglasses'],
        'sunscreen': ['крем'],
        'suspension_bridge': ['мост'],
        'swab': ['швабра'],
        'sweatshirt': ['толстовк'],
        'swimming_trunks': ['плавк', 'бассейн'],
        'swing': ['качел'],
        'switch': ['переключател', 'выключател'],
        'syringe': ['шприц'],
        'table_lamp': ['ламп'],
        'tank': ['танк'],
        'tape_player': ['магнитофон'],
        'teapot': ['чайник'],
        'teddy': ['плюшев'],
        'television': ['телевизор', 'телевиден'],
        'tennis_ball': ['теннис'],
        'thatch': ['солом', 'крыш'],
        'theater_curtain': ['занавес'],
        'thimble': ['наперсток'],
        'thresher': ['комбайн', 'ферм', 'сел', 'сельск'],
        'throne': ['трон'],
        'tile_roof': ['крыш'],
        'toaster': ['тостер'],
        'tobacco_shop': ['табак', 'сигарет'],
        'toilet_seat': ['унитаз', 'туалет'],
        'torch': ['факел'],
        'totem_pole': ['тотем'],
        'tow_truck': ['эвакуатор'],
        'toyshop': ['игрушк'],
        'tractor': ['трактор', 'ферм', 'сел', 'сельск'],
        'trailer_truck': ['грузовик'],
        'tray': ['лоток'],
        'trench_coat': ['плащ'],
        'tricycle': ['велосипед'],
        'trimaran': ['катамаран', 'лодк'],
        'tripod': ['штатив'],
        'triumphal_arch': ['арк'],
        'trolleybus': ['троллейбус'],
        'trombone': ['тромбон', 'труб', 'оркестр'],
        'tub': ['ванн'],
        'turnstile': ['турникет', 'метр'],
        'typewriter_keyboard': ['клавиатура'],
        'umbrella': ['зонтик', 'зонт'],
        'unicycle': ['велосипед', 'колес'],
        'upright': ['пианин', 'piano'],
        'vacuum': ['вакуум'],
        'vase': ['ваз'],
        'vault': ['хранилищ'],
        'velvet': ['бархат'],
        'vending_machine': ['торгов', 'куп'],
        'vestment': ['монах', 'священник'],
        'viaduct': ['виадук', 'мост'],
        'violin': ['скрипк', 'violin'],
        'volleyball': ['волейбол'],
        'waffle_iron': ['вафельниц', 'вафл'],
        'wall_clock': ['час'],
        'wallet': ['кошелек', 'кошельк'],
        'wardrobe': ['гардероб'],
        'warplane': ['истребител', 'бомбардировщик'],
        'washbasin': ['умывальник'],
        'washer': ['стиральн'],
        'water_bottle': ['бутылк', 'вод'],
        'water_jug': ['кувшин'],
        'water_tower': ['унитаз'],
        'whiskey_jug': ['виск'],
        'whistle': ['свисток', 'свист'],
        'wig': ['парик'],
        'window_screen': ['сетк', 'окн'],
        'window_shade': ['штор'],
        'Windsor_tie': ['галстук'],
        'wine_bottle': ['вин'],
        'wing': ['крыл'],
        'wok': ['кастрюл'],
        'wooden_spoon': ['ложк'],
        'wool': ['шерст'],
        'worm_fence': ['забор'],
        'wreck': ['корабл', 'титаник'],
        'yawl': ['корабл', 'лодк'],
        'yurt': ['юрт'],
        'web_site': ['сайт', 'мем', 'прикол'],
        'comic_book': ['комикс', 'аним', 'манг'],
        'crossword_puzzle': ['кроссворд'],
        'street_sign': ['знак'],
        'traffic_light': ['светофор'],
        'book_jacket': ['обложк'],
        'menu': ['мен'],
        'plate': ['пластин', 'металл'],
        'guacamole': ['гуакамол'],
        'consomme': ['суп'],
        'hot_pot': ['гуляш', 'ед', 'поел'],
        'trifle': ['десерт'],
        'ice_cream': ['морожен'],
        'ice_lolly': ['леденец'],
        'French_loaf': ['батон'],
        'bagel': ['рогалик'],
        'pretzel': ['крендел'],
        'cheeseburger': ['чизбургер'],
        'hotdog': ['хотдог'],
        'mashed_potato': ['пюр', 'картофел'],
        'head_cabbage': ['капуст'],
        'broccoli': ['броккол'],
        'cauliflower': ['капуст'],
        'zucchini': ['цуккин'],
        'spaghetti_squash': ['тыкв', 'тыквенн'],
        'acorn_squash': ['тыкв', 'тыквенн'],
        'butternut_squash': ['тыкв', 'тыквенн'],
        'cucumber': ['огурец', 'огурц', 'огурчик'],
        'artichoke': ['aртишок'],
        'bell_pepper': ['перец', 'перц'],
        'cardoon': ['артишок'],
        'mushroom': mushroom_mapping,
        'Granny_Smith': ['яблок', 'яблочн'],
        'strawberry': ['клубник', 'клубничн'],
        'orange': ['апельсин', 'апельсинов'],
        'lemon': ['лимон', 'lemon'],
        'fig': ['инжир'],
        'pineapple': ['ананас'],
        'banana': ['банан', 'banana'],
        'jackfruit': ['фрукт'],
        'custard_apple': ['фрукт'],
        'pomegranate': ['гранат'],
        'hay': ['сен'],
        'carbonara': ['карбонар', 'соус', 'спагетти'],
        'chocolate_sauce': ['паст', 'nutella'],
        'dough': ['выпечк'],
        'meat_loaf': ['мясн', 'рулет'],
        'pizza': ['пицц', 'pizza'],
        'potpie': ['пирог'],
        'burrito': ['буррит'],
        'red_wine': ['вин'],
        'espresso': coffee_mapping + ['эспрессо'],
        'cup': ['чашк', 'кружк'],
        'eggnog': ['коктейл'],
        'alp': ['гор', 'горн'],
        'bubble': ['пузыр'],
        'cliff': ['утес', 'скал'],
        'coral_reef': ['коралл', 'корралов', 'риф'],
        'geyser': ['гейзер'],
        'lakeside': ['озер'],
        'promontory': ['мыс', 'берег'],
        'sandbar': ['песок', 'песчан'],
        'seashore': ['берег', 'пляж'],
        'valley': ['долин'],
        'volcano': ['вулкан'],
        'ballplayer': ['бейсбол', 'спорт'],
        'groom': ['жених', 'свадьб'],
        'scuba_diver': ['акваланг'],
        'rapeseed': ['рапс', 'пшениц', 'пшеничн'],
        'daisy': ['цветок', 'цветк'],
        "yellow_lady's_slipper": ['цветок', 'цветк'],
        'corn': ['кукуруз', 'кукурузн'],
        'acorn': ['желуд'],
        'hip': ['шиповник', 'плод'],
        'buckeye': ['каштан', 'дерев'],
        'coral_fungus': mushroom_mapping,
        'agaric': mushroom_mapping,
        'gyromitra': mushroom_mapping,
        'stinkhorn': mushroom_mapping,
        'earthstar': mushroom_mapping,
        'hen-of-the-woods': mushroom_mapping,
        'bolete': mushroom_mapping,
        'ear': ['зерн'],
        'toilet_tissue': ['туалетн'],
    }

start_server()
